name: Crypto API Processor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, curl, json
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --no-scripts

      - name: Execute tests
        run: vendor/bin/phpunit --colors=always
